# Generated by Django 3.2.9 on 2021-11-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20211125_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
