# Generated by Django 3.2.9 on 2021-11-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
