# Generated by Django 3.2.9 on 2021-11-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_staffperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffperson',
            options={},
        ),
        migrations.AlterModelManagers(
            name='staffperson',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='staffperson',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='staffperson',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffperson',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staffperson',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='staffperson',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='staffperson',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='staffperson',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='staffperson',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='staffperson',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staffperson',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staffperson',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='staffperson',
            name='username',
        ),
        migrations.AlterField(
            model_name='staffperson',
            name='role',
            field=models.CharField(default='Waiter', max_length=100),
        ),
    ]
