# Generated by Django 3.2.9 on 2021-11-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffperson',
            name='notification',
            field=models.TextField(default='No new orders'),
        ),
    ]
