# Generated by Django 3.2.9 on 2021-11-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_staffperson_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffperson',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
